### ISSUE TITLE
Show highlighting in expanded container

### ISSUE THREAD

**Issue by dhelmr** [dhelmr/the-holy-search#15]
Currently, the highlighting disappears when clicking on "Show more", because the html element that contains the highlighed text gets replaced with a new one.

A solution would be to not remove the already existing element, and just add the ones before and after.

**Comment by procrastimax** [comment]
Is this really a bug?
The text used for expanded container is the text from the hash map, which does not contain any highlighting. Or did I missunderstood this issue?

**Comment by dhelmr** [comment]
I think it would still be nice to see the highlighting in the expanded container. But this is not that important right now.

**Comment by procrastimax** [comment]
I think its completely ok to not highlight the expanded text, because the searched terms/ words do not have to do something with the verses before and after the result text. But indeed, highlighting of the result text in the expanding format would be nice.
Best way would probably be to insert the verses before and after the actual result text in the container and not creating an extra textfield, where the specific verses are shown.

**Comment by procrastimax** [comment]
I think this is not going to be done easily with our current implementation, so I'm going to close this.
