### ISSUE TITLE
Refine synonyms

### ISSUE THREAD

**Issue by procrastimax** [dhelmr/the-holy-search#18]
Currently the synonyms are quite a mess.
Because the graph which is spanned by the synonyms in the synonyms files are not completely covering the words which are used in our texts.

In order to fix this, we should only use synonyms of words which are occurring in our texts.
So we should make 3 lists with most used nouns in our texts (maybe 50 most used nouns should be enough). And search for synonyms for those words. Maybe we could again use a synonym API for this, but from my experience those generated words are not really good synonyms.

Also we should change the logic of the synonyms. Currently all synonyms are substituted equally with the syntax: *original, synonym1, synonym2, synonym3*.
Sometimes this leads to really complex graph dependencies. Because one synonym in one line is another synonym in another line and the words which can be substituted for one word get more than doubled. In order to fix this we should try the following syntax in the synonym file:

*synonym1 => original
synonym2 => original
synonym3 => original*

or

*synonym1, synonym2, synonym3 => original*.

By using this kind of synonym syntax, we only have a one-way substitution which (hopefully) leads to more accurate results.

This could also be done after we have all topics and improve synonyms in order to improve accuracy of our search engine.

**Comment by dhelmr** [comment]
> So we should make 3 lists with most used nouns in our texts (maybe 50 most used nouns should be enough). And search for synonyms for those words.

That sounds like a good idea. We can divide the work so that everybody contributes a few synonyms.

 I would like to discuss if we should make separate synonym list for the 3 cores then. Because the most used word in the bible are different from the ones in the koran. If I checked it correctly, the word `Allah` does not yet occur in the synonyms files, but arguably it should be substituted, e.g. when seaching the `BIBLE` and `KORAN` core for `Allah`. In this case, `Allah` should be substituted in the bible with `God` so that comparable results are retrieved.

**Comment by procrastimax** [comment]
> I would like to discuss if we should make separate synonym list for the 3 cores then. Because the most used word in the bible are different from the ones in the koran.

That is totally viable and easily done by the 3 synonym files in each solr core of a book.

For the seconds point of replacing domain specific words with each other, I agree that this could be useful, especially keeping in mind that we should implement a mechanic to copy and search verses from one book in the other books with one click (as Prof. Potthast has mentioned).

**Comment by dhelmr** [comment]
Maybe it is also sufficient to only provide 1 synonyms file that contains also domain-specific keywords for the 3 texts. These domain-specific keyword would not do any harm in the other cores. 

Example: Searching for `Jawhe` -> `Jawhe` will be replaced by `Allah`, so that relevants results for the Koran will be retrieved. For the Torah, the same will be done, but searching for Allah will not yield any results, i.e. not changing the result set. The relevant documents for the Torah will instead be retrieved by the original keyword `Jawhe`.

**Comment by dhelmr** [comment]
Also, Potthast mentioned that we should have a look if there is any research available regarding synonyms for the scriptures. That could really boost the synonym quality as well as reduce the work that we have to do (especially for domain-specific synonyms).

**Comment by procrastimax** [comment]
> Also, Potthast mentioned that we should have a look if there is any research available regarding synonyms for the scriptures. That could really boost the synonym quality as well as reduce the work that we have to do (especially for domain-specific synonyms).

Yeah that could be possible. But we can't really automate this. Because our tanakh and koran texts are community translated we can't be sure to find exactly those words.
The most efficient approach is really to actually analyze the texts we got and find the most used words.

**Comment by dhelmr** [comment]
That's right, I meant to use additional research work as a "knowledge base", when we manually defining the synonyms. I think we all are not experts for the scriptures and there might be many terms that we cannot know.  Example: [https://en.wikipedia.org/wiki/Jeshurun](https://en.wikipedia.org/wiki/Jeshurun) denotes Israel in the Tanakh, and thus should be added as a synonym, but I, at least, did not know that before. 

I think that documents/research in this topic is most likely not linked to Computer Science in general, but rather religious studies/theology.

**Comment by procrastimax** [comment]
Closed for now.
Maybe needing some refinement in the future.
