### ISSUE TITLE
Link to external script resource

### ISSUE THREAD

**Issue by dhelmr** [dhelmr/the-holy-search#6]
Add a link to the expanded box that redirects to another webservice where the whole chapter of the result entry can be read.

(Potthast said this during our presentation)

**Comment by procrastimax** [comment]
Can this be an extern website by someone else? Or do we have to setup another domain for providing whole texts?
I mean can we use something like this: [https://www.bible.com/bible/1/GEN.1.KJV] ?

**Comment by dhelmr** [comment]
Yes, something like bible.com, wikipedia, ...

**Comment by procrastimax** [comment]
Closed with commit: a89065bcfa055630e7730a74f6ef9be68732fb31

Note: This is going to fail some times. Because its just a dumb url creator for specific domains. For bible and tanakh the clear-names of the books are used. Because of differences in translations or formatting it will generate a link which does not exist on the specific domain. But for most verses with "easy" book names it will work.
The quran links are only using numbers, so this will (hopefully) work in all cases.
